name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  english_words: ^4.0.0
  google_maps_flutter: ^2.1.1
  dio: ^4.0.0
  flutter_polyline_points: ^0.2.6
  http: ^0.13.3
  geolocator: ^7.6.2
  url_launcher: ^6.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
  - C:\Users\farou\Desktop\FalconNav\falconn\assets\images\BTSU.jpg
  - C:\Users\farou\Desktop\FalconNav\falconn\assets\images\Carillon_Hall.jpg
  - C:\Users\farou\Desktop\FalconNav\falconn\assets\images\Central_Hall.jpg
  - C:\Users\farou\Desktop\FalconNav\falconn\assets\images\East_Hall.jpg
  - C:\Users\farou\Desktop\FalconNav\falconn\assets\images\Education_Building.jpg
  - C:\Users\farou\Desktop\FalconNav\falconn\assets\images\Founders_Hall.jpg
  - C:\Users\farou\Desktop\FalconNav\falconn\assets\images\Hayes_Hall.jpg
  - C:\Users\farou\Desktop\FalconNav\falconn\assets\images\Kuhlin_Center.jpg
  - C:\Users\farou\Desktop\FalconNav\falconn\assets\images\Maurer_Center.jpg
  - C:\Users\farou\Desktop\FalconNav\falconn\assets\images\McFall_Center.jpg
  - C:\Users\farou\Desktop\FalconNav\falconn\assets\images\Olscamp_Hall.jpg
  - C:\Users\farou\Desktop\FalconNav\falconn\assets\images\Shatzel_Hall.jpg
  - C:\Users\farou\Desktop\FalconNav\falconn\assets\images\Falcon.jpg